### ISSUE TITLE
Utiliser les deux écrans oled 

### ISSUE THREAD

**Issue by orel56** [deverlabs/grappe#2]
Salut, 

j'aurais aimé savoir comment vous aviez fait pour utiliser deux écrans oled identiques ? La communication entre chaque écran et la carte passant par la même adresse I2C (0x78) les deux écrans affichent la même chose. Lorsque j'essaye d'utiliser la fonction "setI2CAddress" de u8g2 cela ne fonctionne pas, néanmoins je sais qu'il y a la possibilité de changer l'adresse I2C d'un des écrans en déplaçant une résistance à l'arrière de ce dernier. Est-ce comme ça que vous avez réalisé le changement d'adresse ? 

Bravo pour votre projet qui est très intéressant !

**Comment by tcardonne** [comment]
Hello,

On a effectivement effectué un changement côté hardware pour pouvoir utiliser les deux écrans de manière indépendante.
Par contre je ne me souviens plus des détails, mais je crois qu'il s'agit bien d'une résistance à rajouter sur un pin spécifique (SA0 d'après ce que je vois).

J'espère que ça t'aideras :-)

**Comment by orel56** [comment]
Salut !

Merci d'avoir répondu aussi rapidement ! Ok très bien, je pense voir quelle résistance déplacer donc je vais essayer ça !

Merci !
